//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameWork.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SpResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrameWork.Resources.SpResources", typeof(SpResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET NOCOUNT ON;  
        ///                            	WITH cte AS (
        ///                            		SELECT p.* 
        ///                            		FROM OrgChartNodes c
        ///                            		JOIN OrgChartNodes p 
        ///                            		ON p.OrgChartNodeId = c.ParentOrgChartNodeId
        ///                            		WHERE c.ParentOrgChartNodeId = @ParentOrgChartNodeId
        ///                            		UNION ALL
        ///                            		SELECT c.*
        ///                            		FROM cte p
        ///                 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetNodeIdsWithParentNodeId {
            get {
                return ResourceManager.GetString("GetNodeIdsWithParentNodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET NOCOUNT ON;  
        ///                            	WITH cte AS (
        ///                            		SELECT p.* 
        ///                            		FROM ProductsGroups c
        ///                            		JOIN ProductsGroups p 
        ///                            		ON p.ProductGroupId = c.ProductGroupParentId
        ///                            		WHERE c.ProductGroupParentId = @ProductGroupParentId
        ///                            		UNION ALL
        ///                            		SELECT c.*
        ///                            		FROM cte p
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetProductGroupIdsWithProductGroupParentId {
            get {
                return ResourceManager.GetString("GetProductGroupIdsWithProductGroupParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET NOCOUNT ON;  
        ///                            	WITH cte AS (
        ///                            		SELECT p.* 
        ///                            		FROM ProductsGroups c
        ///                            		JOIN ProductsGroups p 
        ///                            		ON p.ProductGroupId = c.ProductGroupParentId
        ///                            		WHERE c.ProductGroupParentId = @ProductGroupParentId
        ///                            		UNION ALL
        ///                            		SELECT c.*
        ///                            		FROM cte p
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetProductIdsWithProductGroupParentId {
            get {
                return ResourceManager.GetString("GetProductIdsWithProductGroupParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET NOCOUNT ON;  
        ///                            	WITH cte AS (
        ///                            		SELECT p.* 
        ///                            		FROM Users c
        ///                            		JOIN Users p 
        ///                            		ON p.UserId = c.ParentUserId
        ///                            		WHERE c.ParentUserId = @ParentUserId and c.DomainSettingId = @DomainSettingId
        ///                            		UNION ALL
        ///                            		SELECT c.*
        ///                            		FROM cte p
        ///                        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetUsersIdsWithDomainUserId {
            get {
                return ResourceManager.GetString("GetUsersIdsWithDomainUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET NOCOUNT ON;  
        ///                            	WITH cte AS (
        ///                            		SELECT p.* 
        ///                            		FROM Users c
        ///                            		JOIN Users p 
        ///                            		ON p.UserId = c.ParentUserId
        ///                            		WHERE c.ParentUserId = @ParentUserId
        ///                            		UNION ALL
        ///                            		SELECT c.*
        ///                            		FROM cte p
        ///                            		JOIN Users c 
        ///                    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetUsersIdsWithParentUserId {
            get {
                return ResourceManager.GetString("GetUsersIdsWithParentUserId", resourceCulture);
            }
        }
    }
}
